spring.application.name=SmartLeadQualification

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5332/smart_lead_qualification
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hugging Face
spring.ai.huggingface.api-key=${HUGGINGFACE_API_KEY}
huggingface.base-url=https://router.huggingface.co/v1
huggingface.chat.model=meta-llama/Llama-3.3-70B-Instruct
